name: Test
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - run: |
          sudo apt update
          sudo apt install -y \
            clang-format \
            libcairo2-dev \
            libpango1.0-dev \
            libwayland-dev \
            libxkbcommon-dev \
            scdoc
      - run: make check-format
      - run: make
      - run: ./wvkbd-hello --version
